name: CI

on:
  push:
    branches:
      - master
      - release-*
      - feature/ci-testing
    tags: "*"
  pull_request:

jobs:
  test:
    name: julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          # "1.3" # Fails with `CXXABI_1.3.13' not found
          #- "1.6"
          - "1"
          #- "nightly"
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Check MATLAB Installation
        run: |
          echo "Checking MATLAB installation directory"
          ls /opt/hostedtoolcache/MATLAB/2024.2.999/x64
          echo "Checking MATLAB executable"
          ls /opt/hostedtoolcache/MATLAB/2024.2.999/x64/bin/glnxa64
          echo "Checking MATLAB command"
          more /opt/hostedtoolcache/MATLAB/2024.2.999/x64/bin/glnxa64/run-matlab-command
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: matlab
          path: /opt/hostedtoolcache/MATLAB/2024.2.999/x64/bin/glnxa64
      - name: Run statements
        uses: matlab-actions/run-command@v2
        with:
          command: disp('Hello, MATLAB!');
      # - name: Check MATLAB Installation
      #   run: matlab -batch "disp('Hello, MATLAB!');"
      # - name: Install csh
      #   run: sudo apt-get update && sudo apt-get install csh
      # - uses: julia-actions/julia-buildpkg@latest
      # - uses: julia-actions/julia-runtest@latest
