name: CI

on:
  push:
    branches:
      - master
      - release-*
      - feature/ci-testing
    tags: "*"
  pull_request:

jobs:
  test:
    name: julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.3"
          - "1"
          - "nightly"
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Check MATLAB Installation
        run: |
          echo "Checking MATLAB installation"
          ls /opt/hostedtoolcache/MATLAB/2024.2.999/x64
          matlab -batch "disp('Hello, MATLAB!'); exit"
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
